sudo: false
language: python

addons:
  artifacts:
    s3_region: "us-east-1" # defaults to "us-east-1"
    paths: 
      - /home/travis/build/rcjackson/PyDDA/results/
    bucket: pydda-testing
    target_paths: $TRAVIS_BUILD_NUMBER
    
matrix:
    include:
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
    
install: source continuous_integration/install.sh
script: eval xvfb-run pytest
